# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-06 20:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica', models.CharField(max_length=32)),
                ('kod_pocztowy', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Aukcja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena_minimalna', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_rozpoczecia', models.DateTimeField(auto_now_add=True)),
                ('czas_trwania', models.DurationField()),
                ('liczba_wyswietlen', models.IntegerField(default=0)),
                ('czy_zakonczona', models.BooleanField()),
                ('priorytet', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gatunek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32, unique=True)),
                ('cechy', models.ManyToManyField(to='main.Cecha')),
                ('gatunek_rodzic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gatunek')),
            ],
        ),
        migrations.CreateModel(
            name='Miasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaAukcji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oferta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('czas', models.DateTimeField(auto_now_add=True)),
                ('aukcja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Aukcja')),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Opinia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc_liczbowa', models.IntegerField()),
                ('opis', models.CharField(max_length=255)),
                ('aukcja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Aukcja')),
                ('otrzymujacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otrzymujacy', to=settings.AUTH_USER_MODEL)),
                ('wystawiajacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wystawiajacy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfilUzytkownika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('imie', models.CharField(max_length=32)),
                ('nazwisko', models.CharField(max_length=32)),
                ('numer_domu', models.CharField(max_length=8)),
                ('adres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Adres')),
                ('miasto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Miasto')),
            ],
        ),
        migrations.CreateModel(
            name='Przedmiot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=32)),
                ('opis', models.CharField(blank=True, max_length=1000, null=True)),
                ('zdjecie', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StanNowosci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.CharField(choices=[('n', 'Nowy'), ('u', 'Uzywany')], default='n', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TypAukcji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(choices=[('nor', 'Kupno/Sprzedaz'), ('ang', 'Angielska'), ('hol', 'Holenderska'), ('vic', "Vickerey'a")], default='nor', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TypUzytkownika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.CharField(choices=[('O', 'Osoba'), ('F', 'Firma')], default='O', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WartoscCechyPrzedmiotu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wartosc', models.CharField(max_length=32)),
                ('cecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cecha')),
                ('przedmiot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Przedmiot')),
            ],
        ),
        migrations.AddField(
            model_name='przedmiot',
            name='cechy',
            field=models.ManyToManyField(through='main.WartoscCechyPrzedmiotu', to='main.Cecha'),
        ),
        migrations.AddField(
            model_name='przedmiot',
            name='gatunek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gatunek'),
        ),
        migrations.AddField(
            model_name='przedmiot',
            name='stan_nowosci',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.StanNowosci'),
        ),
        migrations.AddField(
            model_name='profiluzytkownika',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TypUzytkownika'),
        ),
        migrations.AddField(
            model_name='profiluzytkownika',
            name='uzytkownik',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aukcja',
            name='przedmiot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Przedmiot'),
        ),
        migrations.AddField(
            model_name='aukcja',
            name='sprzedawca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aukcja',
            name='typ_aukcji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TypAukcji'),
        ),
    ]
