# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-06 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160506_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stannowosci',
            name='wartosc',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='typaukcji',
            name='nazwa',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='typuzytkownika',
            name='wartosc',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
