# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-06 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160506_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatunek',
            name='cechy',
            field=models.ManyToManyField(blank=True, null=True, to='main.Cecha'),
        ),
        migrations.AlterField(
            model_name='gatunek',
            name='gatunek_rodzic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Gatunek'),
        ),
    ]
