# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-06 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20160506_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatunek',
            name='cechy',
            field=models.ManyToManyField(blank=True, to='main.Cecha'),
        ),
    ]
