# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-08 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160506_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='przedmiot',
            name='zdjecie',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
