# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-08 19:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20160508_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='aukcja',
            name='kupujacy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kupujacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aukcja',
            name='sprzedawca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprzedawca', to=settings.AUTH_USER_MODEL),
        ),
    ]
